version: '3.8'


networks:
  localdev:
      name: localdev

services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "Bigpassw0rd@example.com"
          MSSQL_PID: Express
    container_name: ms-sql-server
    networks:
        - localdev
    ports:
      - "1433:1433"
  api:
    build: .
    depends_on:
      - ms-sql-server
    environment:
        ServerName: "ms-sql-server"
        Database: "currenncydb"
        UserName: "SA"
        Password: "Bigpassw0rd@example.com"
    ports:
      - "8090:80"
    networks:
        - localdev
    volumes:
        - ./tmp:/app/tmp
